Increment17
tony-spark/metrico pull request #33
Opened 2023-01-10 08:51 UTC by tony-spark

2023-01-12 07:34 UTC, Perederey requested changes
В целом хорошо, но нужно
1) переделать бенчамарки (добавть сброс таймера)
2) переделать example, а для этого провести рефакторинг кода
3) мое личное мнение, что бенчмарками хорошо тестировать отдельные алгортимы, сложные функции, а не весь http-handler.
Использу такой инструмент, как Apache JMeter или wrk (либо еще и postman тоже можно настроить) для создания нагрузки на сервер и измерения производительности при реалистичном сценарии нагрузки, это позволит тебе проверить, как сервис ведет себя при реальной нагрузке (а с помощью pprof еще и определить реальные узкие места)

2023-01-12 07:34 UTC, Perederey commented on cmd/agent/main.go
>  	signal.Notify(terminateSignal, syscall.SIGINT, syscall.SIGTERM)
давай еще добавим graceful shutdown)

2023-01-12 07:34 UTC, Perederey commented on docker-compose.dev.yml
> +      - "88:8080"
тут пропустил конец-строки
это последовательность символов, обозначающая конец строки текста в коде. EOL важны для запросов для PR, поскольку они определяют, как текстовые файлы отображаются и обрабатываются в различных операционных системах.

Windows использует комбинацию символов (CR) и перевода строки (LF) для обозначения конца строки, в то время как Linux и macOS используют только символ перевода строки (LF).

Представь, если разработчик создает файл на Windows, а затем отправляет запрос на исправление с этим файлом, файл будет содержать CR+LF EOL. Но если этот файл затем будет извлечен и объединен в репозиторий на macOS, символы CR вызовут проблемы при редактировании)

**По этой причине для PR важно, чтобы текстовые файлы были последовательны в использовании EOL.**

IDE можно настроить чтобы перед запуском он добавлял такую штуку

2023-01-12 07:34 UTC, Perederey commented on internal/agent/metrics/memory_test.go
> +	mc := NewMemoryMetricCollector()
по-хорошему нужно вызывать resetTimer, после того как создаешь объект

2023-01-12 07:34 UTC, Perederey commented on internal/agent/metrics/metrics_test.go
> +	}
тут также не хватает сбора таймера

2023-01-12 07:34 UTC, Perederey commented on internal/server/example_server_test.go
> +func Example() {
нереально огромный пример получился, запутанный и сложно читаймый. Дававай думать как переделать)

1) выдели отдельно создание сервера 
2) логику реквеста также можно сделать и вынести в сервис 

Задача сохранить макимум строчек 7 кода в example

Сейчас же тут много-много всего(

2023-01-12 09:58 UTC, tony-spark commented on cmd/agent/main.go
>  	signal.Notify(terminateSignal, syscall.SIGINT, syscall.SIGTERM)
Я до него обязательно скоро доберусь) #30

2023-01-15 06:55 UTC, tony-spark commented
Использовал связку Postman+k6 (есть конвертер postman->k6)

БД 
![image](https://user-images.githubusercontent.com/27339207/212527268-d77b875e-e303-45bb-8e17-58591ef7ecdc.png)

Inmem + flush to file
![image](https://user-images.githubusercontent.com/27339207/212527282-429a30a3-f5c9-483b-a67b-6230a94f3f8e.png)

2023-01-20 15:02 UTC, Perederey approved these changes
теперь все отлично!

2023-01-20 15:12 UTC, merged